In [1]:
import numpy as np



In [2]:
np.random.rand(30)

array([0.2604092 , 0.57338779, 0.19031898, 0.62032607, 0.6796994 ,
       0.29193314, 0.22891131, 0.23796877, 0.26398449, 0.56042173,
       0.24576241, 0.4158837 , 0.9855498 , 0.04864689, 0.17347516,
       0.5912625 , 0.80594545, 0.26798702, 0.90276864, 0.18418429,
       0.17921178, 0.21682457, 0.5434434 , 0.20770474, 0.43592815,
       0.17756921, 0.27053518, 0.4422079 , 0.9098517 , 0.17610667])

In [3]:
from  sklearn import datasets

In [ ]:
numpy range can be done by the key word arange and limits

In [4]:
arr = np.arange(1,11)



In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[1:8]


array([2, 3, 4, 5, 6, 7, 8])

In [7]:
arr[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
arr[0:5] =100

In [9]:
arr


array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
numpy indexing and selection



In [1]:
import numpy as np
arr = np.array([[2,34,5],[3,5,6],[8,4,7]])

In [2]:
arr

array([[ 2, 34,  5],
       [ 3,  5,  6],
       [ 8,  4,  7]])

In [ ]:
array arrange with a limit

In [ ]:
arrayindexing

In [5]:
import  numpy as np
arr = np.array([[2,34,5],[3,5,6],[8,4,7]])
print(arr)
arr[1][1]
arr[1]

[[ 2 34  5]
 [ 3  5  6]
 [ 8  4  7]]


array([3, 5, 6])

In [6]:
arr[:2]

array([[ 2, 34,  5],
       [ 3,  5,  6]])

In [7]:
dd = np.arange(50).reshape(5,10)

In [8]:
dd

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
numpy opertaions

In [ ]:
array with array operation

In [11]:
import numpy as np
arr1 = np.arange(0,10)


In [12]:
arr1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr1+arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
arr1 *5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [17]:
np.max(arr1)

9

In [18]:
arr1.max()

9

In [22]:
c = np.zeros(10)

In [23]:
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
d =np.ones(10)

In [25]:
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
print even integer upto 50

In [27]:
 np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])